FROM oven/bun:1-alpine

WORKDIR /app

COPY --chown=bun:bun package.json bun.lock ./
USER bun
RUN bun install

COPY --chown=bun:bun . .

CMD ["bun", "run", "dev", "--hostname", "0.0.0.0", "--port", "3500"]
